### PR TITLE
changed php version during phar creation

### PR DESCRIPTION
**Pull request by AlessandroMinoccheri**
I changed the PHP version from `7.4` to `7.1` to solve this issue: #242 
In my opinion, this can create future problems, I don't know at the moment if the option `target-php-version` is enough or we have to create a phar version for each PHP version.

### CODE REVIEW

**Comment by fain182** [comment]
Do you think it might be worth creating some tests?

**Comment by AlessandroMinoccheri** [comment]
Yes @fain182, but you need to create a phar file and try it with different containers with different PHP versions.

**Comment by micheleorselli** [comment]
Makes sense to me as we should use the lowest PHP version we support in composer.json

IIRC that was the case at the beginning, did we change it for a reason? 🤔

**Review by micheleorselli — APPROVED** [review]
Looks good to me then :-)

**Pull request merged**
