### PR TITLE
Add exclude root

### PR DESCRIPTION
**Pull request by notcgi**
https://github.com/phparkitect/arkitect/issues/338

### CODE REVIEW

**Comment by AlessandroMinoccheri** [comment]
Hi @notcgi can you please fix the CI?

**Comment by notcgi** [comment]
> Hi @notcgi can you please fix the CI?

done

**Comment by fain182** [comment]
Exclude root namsepace is not the same thing as excluding the PHP built-in classes... but anyway is a solution we can evaluate.

**Comment by AlessandroMinoccheri** [comment]
@notcgi when do you think is useful to exclude root classes?

**Comment by notcgi** [comment]
> @notcgi when do you think is useful to exclude root classes?

Domain and Application layers can have dependencies like Datetime(-Immutable), Exception, Throwable, RuntimeException, UnitEnum etc

**Comment by AlessandroMinoccheri** [comment]
Thank you @notcgi

**Pull request merged**
