### PR TITLE
Increase the psalm error level from 3 to 2

### PR DESCRIPTION
**Pull request by AlessandroMinoccheri**

### CODE REVIEW

**Comment by micheleorselli** [comment]
it seems the build problem is related to composer, as it complains about unsupported PHP version

**Comment by AlessandroMinoccheri** [comment]
The same problem is in the other PR too:
https://github.com/phparkitect/arkitect/pull/252

We can try to use for example `version: 1` instead of `version: 2` @micheleorselli

**Comment by AlessandroMinoccheri** [comment]
Yeah, it was that now it's all green.
Do you think that it's better to solve the problem in another little PR moving last commit from here @micheleorselli ?

**Comment by micheleorselli** [comment]
let's stick with version 2. composer 1 is unsupported and slow as hell. Version [2.2.12](https://github.com/composer/composer/releases/tag/2.2.12) should be compatible with our PHP version

**Comment by AlessandroMinoccheri** [comment]
@micheleorselli I tried with composer 2 and that specific version without success.

**Review by micheleorselli — APPROVED** [review]

**Pull request merged**
