### PR TITLE
Fix fatal error on startup with Symfony 7.x due to changes in command naming

### LINKED ISSUE #419: Fatal error on start with `symfony/console` 7.x due to changes in command names
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Library Version | 0.3.27
| PHP version     | 8.3.1

#### Summary

When running PHPArkitect with `symfony/console` 7.x, a fatal error immediately happens.

#### Current behavior

```
PHP Fatal error:  Uncaught Symfony\Component\Console\Exception\LogicException: The command defined in "Arkitect\CLI\Command\Init" cannot have an empty name. in /<snip>/vendor/symfony/console/Application.php:535
```

#### How to reproduce

Run PHPArkitect with `symfony/console` 7.x installed.

#### Expected behavior

Works

### PR DESCRIPTION
**Pull request by ben-challis**
Fixes #419 

Aligns with `Check` command which does:

```php
    public function __construct()
    {
        parent::__construct('check');
    }
```

### CODE REVIEW

**Comment by vibby** [comment]
Thank you for PR, I was just starting to propose it too :) Can you please run php-cs-fixer to fix CI @ben-challis ?

**Comment by ben-challis** [comment]
The code style issues look to be unrelated to the changes in this PR and pre-existing but yep sure, I'll do it in a separate PR

```
src/Analyzer/NameResolver.php (phpdoc_add_missing_param_annotation, fully_qualified_strict_types, no_superfluous_phpdoc_tags)
```

**Comment by ben-challis** [comment]
@vibby https://github.com/phparkitect/arkitect/pull/421

**Comment by vibby** [comment]
Can you merge this too please @fain182 ?

**Pull request merged**
