### PR TITLE
Skip isFinal check on traits & add IsTrait and IsNotTrait rules

### PR DESCRIPTION
**Pull request by simivar**
As traits can not be final assertion that those are final should not be performed

### CODE REVIEW

**Comment by simivar** [comment]
This is now in the state available for review 😄 when you have some free time may I please @AlessandroMinoccheri

**Comment by fain182** [comment]
Thank you for your contribution @simivar!
We just fixed the problem of traits with the isFinal, if you align to the main branch, we can merge the `IsTrait` and `IsNotTrait` rules that can be a nice addition :slightly_smiling_face:

**Comment by simivar** [comment]
@fain182 done :)

**Comment by simivar** [comment]
@fain182 fixed tests

**Review by AlessandroMinoccheri — APPROVED** [review]
LGTM 👍

**Pull request merged**
