### PR TITLE
Implement MatchOneOfTheseNames

### LINKED ISSUE #362: Support OR in HaveNameMatching
This discussion: https://github.com/smortexa/laravel-arkitect/issues/19 raise the problem to have a rule that can express "have a name matching X or Y".

It could be implemented by passing an array of pattern to the `HaveNameMatching` or maybe creating a new rule named `HaveNameMatchingOneOf` or something similar.

### PR DESCRIPTION
**Pull request by szepeviktor**
Fixes #362
@fain182

### CODE REVIEW

**Comment by fain182** [comment]
Thanks! 
Could you add some tests? 
If you want some inspiration you can check this: https://github.com/phparkitect/arkitect/blob/main/tests/Unit/Expressions/ForClasses/ExtendTest.php

**Comment by szepeviktor** [comment]
This is all I have. Depression is in my reach as I only **read* unit tests.

**Review by AlessandroMinoccheri — APPROVED** [review]
LGTM 👍

**Review by fain182 — APPROVED** [review]

**Comment by smortexa** [comment]
@fain182 @szepeviktor Implementing this approach for other methods is such a good idea.

**Pull request merged**
