### PR TITLE
Add ability to check for multiple extends

### PR DESCRIPTION
**Pull request by kapersoft**
This PR adds the ability to add multiple parameters in the `Extends` constructor. The violation will happen when none of the given strings will match the extend.

In my project I want to check if unit tests extends PHPUnit's TestCase or Mockery's TestCase:
```php
return static function (Config $config): void {
    $testClassSet = ClassSet::fromDir(__DIR__ . '/Tests');

    $rule = Rule::allClasses()
        ->that(new ResideInOneOfTheseNamespaces('Tests\Unit'))
        ->andThat(new HaveNameMatching('*Test'))
        ->should(new Extend(\PHPUnit\Framework\TestCase::class, \Mockery\Adapter\Phpunit\MockeryTestCase::class))
        ->because('unit tests must extend the PHPUnit TestCase or Mockery TestCase');

    $config->add($testClassSet, $rule);
};
```

When one parameter is used in the `Extend` constructor, it works the same as before.

### CODE REVIEW

**Comment by AlessandroMinoccheri** [comment]
Hi @kapersoft  thanks for this PR, can you please also update the README file with this new behavior?

**Comment by kapersoft** [comment]
@AlessandroMinoccheri I have applied the same changes to the `NotExtend`-class and updated the readme.md

**Comment by AlessandroMinoccheri** [comment]
Little fix to do @kapersoft for coding standards, then it can be merged.

**Comment by kapersoft** [comment]
@AlessandroMinoccheri ✅ Done.

**Review by AlessandroMinoccheri — APPROVED** [review]
LGTM 👍

**Comment by kapersoft** [comment]
Thanks! 👍

**Pull request merged**
