### PR TITLE
Fixed "IsFinal" for Enums

### PR DESCRIPTION
**Pull request by sebastianstucke87**
Fixed `\Arkitect\Expression\ForClasses\IsFinal` along with various `Arkitect\Analyzer`-classes because:
- Traits can not be final

### CODE REVIEW

**Comment by sebastianstucke87** [comment]
Sorry, but I don't understand this error: https://github.com/phparkitect/arkitect/actions/runs/4693985646/jobs/8321648237?pr=381#step:8:16

**Comment by AlessandroMinoccheri** [comment]
Hi @sebastianstucke87, thanks for this PR :)
Can you please align the branch with main?

Thank you.

**Comment by fain182** [comment]
> Sorry, but I don't understand this error: https://github.com/phparkitect/arkitect/actions/runs/4693985646/jobs/8321648237?pr=381#step:8:16

It's just a style error... if you run `make build` they will be solved automatically, and you can commit the result :slightly_smiling_face: 

The code looks good to me, but I suppose we need to restrict the tests to only some version of PHP (> 8.1) like we did here:
https://github.com/phparkitect/arkitect/blob/da20cdc9278e3bef747ac6d594200d7344e6d0ca/tests/E2E/PHPUnit/CheckClassHaveAttributeTest.php#L14

**Review by AlessandroMinoccheri — APPROVED** [review]
LGTM 👍

**Review by fain182 — APPROVED** [review]

**Pull request merged**
